# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_wanted_project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'GoogleSignIn'
pod 'Firebase/Core'
pod 'Cosmos', '~> 9.0'
pod 'Firebase/Storage'
  # Pods for ios_wanted_project

end
